name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - name: Generate release notes
        run: ./scripts/release-notes.sh ${{ env.VERSION }}
      - name: Create release
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --rm-dist --release-notes ./RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}